services:
  fastapi:
    image: rag-api:dev
    container_name: rag-api
    ports:
      - "8080:8000"
    volumes:
      - ./api:/app/api
      - ./retrieval:/app/retrieval
      - ./data:/app/data
      - ./requirements.txt:/app/requirements.txt
      - huggingface-cache:/root/.cache/huggingface
    depends_on:
      - qdrant
    environment:
      - PYTHONUNBUFFERED=1
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

volumes:
  huggingface-cache:
